### ISSUE TITLE
Russian translation удачи

### ISSUE THREAD

**Issue by i0natan** [i0natan/nodebestpractices#105]
https://github.com/i0natan/nodebestpractices/tree/russian-translation

@demid5111 - Russian translation can be officially kicked-off. You're the lead! I'll be at your disposal should you need anything. A branch was created (link below), you should have permissions to it, everyone else must PR before changing anything there.

I would ask/recommend only 2 important guidelines:

Keep the same content & formatting - the focus is on translation, should anyone want to modify the content or the graphics - let's PR first in English and them translate to Spanish
Duplicate pages - the content should be translated over a page duplication. Readme.MD became Readme.russian.MD, all other files should be duplicated similarly. So the number of English & Russian pages should be the same. You already have readme.russian.md & sections/breakintcomponents.russian.md - kindly create all other page duplication (feel free to ping should you need help). Will create a bold link from the English home page to the Russian home page (with bold credit of course...).

https://github.com/i0natan/nodebestpractices/tree/russian-translation

**Comment by i0natan** [comment]
@demid5111 no rush, just checking whether everything is clear and if I assist in anyway

**Comment by demid5111** [comment]
@i0natan yep, it is all clear  - it is WIP, hope to create first PR till EO ww3. Thank you so much for assistance!

**Comment by i0natan** [comment]
Sounds great and looking forward

**Comment by oshliaer** [comment]
# Russian translation resume

There are three PRs/threads for the start translate:

1. The first initiative #98 #105
2. The second attempt is @GraxMonzo PR #388
3. The third attempt is #433 

As I can see now we cannot coordinate to form a group for active participation. It's sadly because I find the Practices very useful.

# My suggestions

1. Reopen #105 because this topic is already referenced by all translations.
2. Close #388 with reject. I cant merge this softy.
3. Review #433

**Comment by i0natan** [comment]
@oshliaer Sounds good

**Comment by oshliaer** [comment]
Related #454
