### ISSUE TITLE
Sanitizing user input - how?

### ISSUE THREAD

**Issue by i0natan** [i0natan/nodebestpractices#192]
@lirantal @js-kyle @BrunoScheufler  I'm writing now about sanitizing user input (as part of our security best practices #133), having doubts about the recommended techniques. Ideally, I would love to have a single middleware that sanitizes the entire input (i.e. remove script tags, sql commands, etc). Practically, I can't find a library that acts that way + this approach has significant performance footprint. Most libraries like xss-filters & express-validator act on specific routes and fields which forces the developer to deal with security concerns as she codes business features. What do you think?

**Comment by lirantal** [comment]
There are definitely some general purpose libraries out there, either by OWASP or the one provided by Yahoo but in general, I don't think you want to implement a one-fits-all kind of middleware that will always strip everything.

More than that, it is preferred that you either entirely disregard the request or accept it as is but then be sure to apply output encoding properly. This is due to the fact that sanitizing data is a tough task and it's a blacklist mechanism rather than a whitelist, which is least efficient and always needs to be update with new patterns to sanitize.

**Comment by i0natan** [comment]
@lirantal Any particular libraries recommendations about output encoding? reference to other material on this?

**Comment by lirantal** [comment]
https://github.com/ESAPI/node-esapi
https://github.com/component/escape-html
https://github.com/mathiasbynens/cssesc
https://github.com/joliss/js-string-escape

**Comment by i0natan** [comment]
@lirantal Thanks. I saw some of these libraries but none looked popular enough, hoped there is some dominator on this field
