### ISSUE TITLE
November maintenance

### ISSUE THREAD

**Issue by js-kyle** [i0natan/nodebestpractices#277]
**Maintainer on call**: @BrunoScheufler 

**Updates**
- [x] Update top badges with best practices item count, last update date and Node.js version
- [ ] Ensure all translations are aligned with the English version
- [x] Update 'thank you' stars & flowers
- [ ] Notify and thank the contributors of the month

**Flowers**
- @david-szabo97 
- @blackmatch 
- @ISNIT0 
- @marcelosdm 

**Stars**
- Corey Cleary @coreyc 

**Translation work**
- @blackmatch (🇨🇳)
- @marcelosdm (🇧🇷)

**Comment by BrunoScheufler** [comment]
thanks @js-kyle!

**Comment by i0natan** [comment]
@js-kyle Aren't translators assigned flowers?

**Comment by BrunoScheufler** [comment]
@i0natan I'm not sure what our concensus on that was. They are definitely mentioned in the translation section, as credits to the parts they've worked on

**Comment by i0natan** [comment]
@BrunoScheufler Let's be generous... 😆

I would assign flowers, it very intensive and valuable work

**Comment by ISNIT0** [comment]
Hey guys,
I'm new here, but happy to muck in - I'll have a look around, but please do feel free to tag me in anything that a newbie can do!

**Comment by i0natan** [comment]
@ISNIT0 Welcome! Glad to have you here

Which of the above seems like tasks you're comfortable with:
- Export our repo as a website (there are tools that do that)?
- "Translating" JS examples to TS?
- Add this repo to various Github awesome lists [like this for example](https://github.com/sorrycc/awesome-javascript)?
- Setting up circleCI markdown linting job?
- Organize vendors: many bullets have recommendation for specific vendors/packages, we want to ensure that we mention only [leading vendors as stated in our writing guideliness](https://github.com/i0natan/nodebestpractices/blob/master/.operations/writing-guidelines.md)

**Comment by BrunoScheufler** [comment]
@i0natan I'll take on these changes this weekend 👍

**Comment by MorganConrad** [comment]
Sorry if this is the wrong place, but didn't want to raise it as an actual "issue".  Related to "6. Adjust the HTTP response headers for enhanced security" and "7. Constantly and automatically inspect for vulnerable dependencies", on thing I dislike about Helmet, which is otherwise solid and well respected, is that it depends on **a lot** (14) of other modules.  So I wrote [kepi](https://www.npmjs.com/package/kepi), which has 0 dependencies, is much smaller, and more flexible, in that you can set non-security related headers as well.

I'm no security expert, nor an HTTP Headers expert, so kepi definitely needs somebody to review it.  But, when you have a chance, if you could review it, provide comments, and possibly suggest it in section 6 as an alternative to helmet, I'd appreciate it.  Thank you.

**Comment by BrunoScheufler** [comment]
@ISNIT0 @blackmatch @david-szabo97 @marcelosdm thank you so much for your countless efforts and contributions throughout November!

@coreyc thank you for improving our project content-wise, you're making this whole project even bigger and better!

**Comment by BrunoScheufler** [comment]
@MorganConrad thanks for your suggestion! We'll take a look into that and evaluate if it's eligible to be added as an alternative 👍 So far we've just picked the most used tools as you can imagine, but with all the recent trouble around the `flatmap-stream` package it's definitely smart to depend on the least amount of unknown code. We'll definitely reach out to you again when there's progress on the process 😃
