### ISSUE TITLE
November meeting proposed agenda

### ISSUE THREAD

**Issue by i0natan** [i0natan/nodebestpractices#286]
- General feel & feedback
- Growing into an organization
- Raising funds for future projects (e.g. Noko)
- Pushing forward the performance section
- Maintaining existing sections - security, production, testing

@sagirk @js-kyle @BrunoScheufler @idori

**Comment by BrunoScheufler** [comment]
Great meeting 🎉 

I'll add some notes to the points we discussed

- Growing into organization
  - naming is important to stay flexible for future project development, the Node.js best practices repository should keep its established name, but the organization name could be chosen more freely 
  - everybody should be able to contribute <-> we need some kind of governance to keep quality and enforce guidelines, many big OSS-projects implement a system where everybody who's contributing is a part of the organization and important decisions are made by a committee
  - a problem of the system mentioned above would be that our project is different in reviewing content, guidelines, language, etc. so it might not work out as intended
  - we should provide a contribution entrypoint for new and existing contributors, either by creating a well-maintained repository full of tasks or using some kind of project/issue board (maybe GitHub's projects feature)
- Raising funds for further work
  - a platform to handle financial contributions transparently: [Open Collective](https://opencollective.com/) (already used by webpack, Babel, Codesandbox)
- Performance section
  - we should focus on increasing the draft-to-publication speed by collaborating on each point and instead of releasing the whole section in a batch, rather publishing single points once they're ready

**Comment by i0natan** [comment]
@BrunoScheufler Great summary.

Any Ideas on how we encourage people to write?

**Comment by BrunoScheufler** [comment]
@i0natan I think there are many people who would like to contribute, maybe it will be easier once we design our issue system in a more accessible style, using tags etc., so that everybody can get started quicker 🚀

**Comment by i0natan** [comment]
Sounds cool. Let's split the work, who wants to:
1. Check for organization names
2. Create opencollective page (once we have that page all of us should approach backers)
3. Open a performance project/issue - something that shows ideas for BP along with their status. Like those beautiful tables that @js-kyle was creating for the security writing

Thoughts and questions on the process changes (given that writing new best practices is not as challenging as contributing 5 lines of code to some repo):
- Onboarding new maintainers - Shall we indeed onboard anyone who PR successfully or apply a bit more selective choice?
- Ensuring content quality - now that we encourage BPs from more people, we need to raise the writing and approval bar by (A) Adding more tools like markdown CI, enrich the content writing guidelines (B) Carefully collaborate on new BP PR, each must undergo  2 improvements cycles where at least 2 of us contribute ideas and approve

@BrunoScheufler @js-kyle @sagirk

**Comment by BrunoScheufler** [comment]
@i0natan let's wait with all decisions towards organizational stuff like maintainer onboarding until we've switched to an organization, maybe it will have features for us to use and we can decide easier than currently.

Reviewing and optimizing new and existing content is more important now than ever, so we'll have to assign some resources to it. If it works out with my time, I'll review every PR to enforce our style & code guidelines, for the translations, we'd have to apply a flow of multiple steps, because checking the language will have to be done by a language-native person 👍

**Comment by js-kyle** [comment]
My two cents - I'd lean towards being more selective (we acknowledge contributions on our README), then contributors who are motivated & contributing lots could be onboarded.

**Comment by js-kyle** [comment]
Org name idea:

bestpractices.io (we could get ownership of that and have a nice static page)

bestpractices.io/nodebestpractices
bestpractices.io/noko
bestpractices.io/dockerbestpractices

**Comment by sagirk** [comment]
As far as names go, I think all of us are converging on `bestpractices`.

Organization: github.com/bestpractices
Homepage: bestpractices.guide (bestpractices.io is taken already)
