### ISSUE TITLE
Alternative Delivery Methods

### ISSUE THREAD

**Issue by ISNIT0** [i0natan/nodebestpractices#297]
- Interactive HTML View
   GitHub view already does this, but it can't easily be viewed or distributed without GitHub (and a working internet connection)
    I guess we have a couple of options for this:
    - Inline everything into a single HTML file (CSS, JS, Images, other MD files)
    - Generate an archive (Zip) with all assets and pages separate (this also makes it easily browsable)
- PDF (#258)
  This obviously would be easy to share, but as it's static, we would need to inline all locally referenced content.

Inlining content makes the document harder to scan

One solution to this is to add all referenced documents to the end of the file and use "view more" hyperlinks which scroll the page to somewhere near the end of the file.

@i0natan @BrunoScheufler What're your thoughts?

**Comment by js-kyle** [comment]
Something using Service workers(for offline support/PWA) could be nice, that would probably be closest to the first option here

**Comment by ISNIT0** [comment]
@js-kyle In all honesty, I think even plain old vanilla JS would do the trick 😄

**Comment by BrunoScheufler** [comment]
@ISNIT0 great thoughts! I think the main task for generating a separate page with all the content we can then later convert to a PDF would be to scrape the main README (in multiple languages) and inline the specific sections at the bottom end, making it a unified page for both short information and details. However this document might get fairly big due to the size of our project, so I'm not completely sure how to address performance issues arising from this. Generally speaking, rendering markdown as html is really easy using some common libraries, and converting it to pdf is also straightforward with something like puppeteer or an external service.

**Comment by i0natan** [comment]
@ISNIT0 @js-kyle @BrunoScheufler 

What are the goals? what problems do we aim to solve?

For example, from my perspective, one sponsor asked from me to duplicate the content also to a website so we gain more visitors and he increases the exposure.

**Comment by BrunoScheufler** [comment]
@i0natan exporting our complete contents to a website is already working, as demonstrated by @ISNIT0's proof of concept PR 👍 There's not many problems I guess, most are just thoughts on implementation things
