### ISSUE TITLE
 What is the difference between dal and service and controller

### ISSUE THREAD

**Issue by ItayElgazar** [i0natan/nodebestpractices#314]
@i0natan 
Hey, just saw your message on the other issue.

What is the difference between dal and service and controller?
Today the DAL is communicating with the db, and the controller invoke the dal functions.
for example:
controller: 
`
getAll() { 
dal.getAll().then((res) => {
 // some code 
});
}`

So for what do I need to use service?

Thanks!!!

**Comment by i0natan** [comment]
Hey @ItayElgazar! 

What other issue? please link

I'll answer this shortly

/remind me in 1 day

**Comment by NitinHsharma** [comment]
**DAL (Data access layer):**
As you said "Today the DAL is communicating with the DB and your controller is calling DAL." as per my knowledge DAL is introduce in the system so that your business logic should not depend upon the database you are using. So suppose today you are using MongoDB and tomorrow you want to shift on to Cassandra the only thing which you have to change is DAL. But in this case all the function call or for more accurate I should say the interface will be the same for all the databases.
What we generally do we have created the single DAL for all the databases which we are using in a different application with a common interface while creating the object of DAL you have to pass the parameter for selecting DB. something like below
```
const DbClient = new DAL('mongo', 'MongoDB://localhost:27017/admin');
```
from param1, we have to understand which DB we have to make the connection.


**Controller**
It is mainly putting all application components together into a controller, It uses services and DAL to complete the work and serving response.

**Services**
It is mainly like the work which is common can be used in multiple controllers.
Example: Using any other microserive. It's better to keep your business clean so instead of implementing any third-party service (any service apart from your project) in any controller create the separate service which deals with it and provides a function to the controller.   

NOTE: ALL THIS IS BASED ON MY NOOB KNOWLEDGE PLEASE CORRECT ME IF I M WRONG ANYWHERE. :)

**Comment by i0natan** [comment]
@ItayElgazar Sorry for not replying in a timely manner, busy days :]

Simply put, the controller comes before the service in the layers chain and unlike the service, contain no business logic.

Historically, 'Controller' and 'Service' come from different 'stories': MVC is a pattern that was created and used mostly for UI ([see bullet 3 here](https://medium.com/@me_37286/19-ways-to-become-a-better-node-js-developer-in-2019-ffd3a8fbfe38) and then adopted for the backend in agile languages like Ruby. In a traditional backend architecture, there's less usage of the term controller.  

A controller is part of the application layer which is responsible to take some input,  figure out what to do with it and dispatch the work to the business logic layer. It shouldn't include any business logic but some use it to orchestrate some business logic units (services).   

Service, on the other hand, is part of the business logic (a.k.a domain layer), it's responsible to run some app flow and also invoke the DAL when necessary.

Practically, you might use it in one of two forms:
- Thin application layer - The orderController will get API requests and call orderService which holds the business logic. The controller does not more than handling application concerns like error handling. Consider not using the word Controller rather the application name, for example orderAPI, orderCRONJob, orderCommandLine
- Richer application layer - Here the controller will invoke multiple services and gain reusability and flexibility by having multiple similar routes that use the same business logic for different scenario. For example:
/order/memberClub controller will call basicOrderService and then the memberClubRewardService 
/order/gift controller will call basicOrderService and then the giftService 

@ItayElgazar What about the Hebrew translation, let's push it?

@NitinHsharma Welcome. Your explanation is great and I like your approach: even when you're a noob, try thinking and proposing your view. This is the only way to practice and train your brain.

**Comment by ItayElgazar** [comment]
@NitinHsharma @i0natan Got it. 
Thank you both for amazing explanation. 
@i0natan Let's push it. I will fork this repo, we can pair together if you like.
