### ISSUE TITLE
January meeting proposed agenda

### ISSUE THREAD

**Issue by BrunoScheufler** [i0natan/nodebestpractices#319]
New year, new meeting 🎉 😄 

**Discussed points**

- The organization migration will be on-hold as we'll further discuss benefits and drawbacks of transitioning
  - Future projects will certainly be part of the organization, the main repo will stay under @i0natan 👍 
- Structure of project collaborators will change to a system similar to the Node.js organization (points below are a draft, currently)
  - A steering committee will manage and organize the direction all of our projects are heading
  - Collaborators will be chosen by valuable contributions to any of our projects
- We've reorganized and collected some projects
  - Publish nodebestpractices as website/PDF (hooks into CI)
  - Integration of TypeScript code examples, maybe replacement of old examples
  - Grammar & language optimization (e.g using proselint)
  - CI for all use cases (code-linting, exporting to pdf, etc.)
  - Introduce news/updates section in the main README containing recent changes
- Optimizing contribution quality
  - Add PR template with checklist that refers to writing guidelines (using links)

**Comment by i0natan** [comment]
(A message to bot below)
/remind me in  days

**Comment by i0natan** [comment]
(A message to bot below)

/remind me to comment in 2 days

**Comment by TheHollidayInn** [comment]
Are you open to other people joining these meetings now or are they closed?

**Comment by i0natan** [comment]
@TheHollidayInn We plan now to create a collaborators group, each collaborator will hold a project (see lists below), access to handle some PRs, there will be a periodical collaborators meeting. You're more than welcome to hold some project and join the collaborator's group, let just first refine this model for a few days

@BrunoScheufler Great summary, let's assign action items? I'm proposing below who should handle what, feel free to change. I suggest that each one of us will create a GitHub project for his work-stream and assign deadlines

- News & updates section - @idori 
-  Create a .opertions/contribution-model.md file that explains about our management model + two parts at readme.md: Steering Committee + Collaborators. We should elaborate there how to become a collaborator, what happens when steering member or collaborator stops contributing, etc. I would make it an inviting text that encourage contribution  - @js-kyle 
- Publish nodebestpractices as website/PDF (hooks into CI) - @BrunoScheufler or @idori 
-  Lead the stream of adding TS examples to all BPs - @sagirk 
- CI for all use cases (code-linting, exporting to pdf, etc.) - @i0natan
- Grammar & language optimization (e.g using proselint)- @BrunoScheufler 
- Strict content writing guidelines with a checklist and a PR template - @i0natan 

@BrunoScheufler @sagirk @js-kyle Thoughts?

**Comment by BrunoScheufler** [comment]
@i0natan since I don't have much experience with CI right now and as @sagirk suggested CI-based tooling, you could assign him to "CI for all use cases" and publishing the repo as a website/pdf (work for that is already being done by @ISNIT0), if he's okay with it of course. I'd be fine to take on the TS transition in return 👍 I think this covers ideas from our meeting a bit more 😄

**Comment by ISNIT0** [comment]
I'm happy to contribute to CI, TypeScript conversion and the PDF generation if I'm asked to do a specific task - I don't really have enough time to go and find myself tasks 😄

**Comment by BrunoScheufler** [comment]
@ISNIT0 great to hear that! We'll be spending some time on organizing our current projects and tasks and list them in a way that's easier for new and existing contributors to figure out what can be worked on 😄

**Comment by i0natan** [comment]
@ISNIT0 I've also experienced with CIs so it could be great to work together on this work-stream, let's open a project and split the tasks? If yes, I can do this so it will be easier for you as @BrunoScheufler said

**Comment by i0natan** [comment]
@BrunoScheufler Can you create an example project with deadline and well-explained tasks so/external collaborators will be able to jump in easily?

**Comment by BrunoScheufler** [comment]
@i0natan sure, will try to aggregate all of our current tasks 😄 Might take some time though, I'll notify you once it's done!

**Comment by ISNIT0** [comment]
@i0natan  Happy to team up there!

**Comment by i0natan** [comment]
> sure, will try to aggregate all of our current tasks 😄 Might take some time though, I'll notify you once it's done!

@BrunoScheufler Don't stretch yourself too thin, we just need one example project with few deadlines  tasks -> then let each assignee define his own deadlines & tasks

If too busy in the next few days, I can create one



> Happy to team up there!

@ISNIT0 Very cool, pinging once a project is created

**Comment by BrunoScheufler** [comment]
@i0natan will immediately do that tomorrow, in which format would you like the tasks issues? Like GitHub issues or rather a list of tasks in written form, etc?

**Comment by i0natan** [comment]
@BrunoScheufler Your call, come with your suggestion for a convenient and effective template
