### ISSUE TITLE
Component prefix

### ISSUE THREAD

**Issue by huquduy** [i0natan/nodebestpractices#78]
Do we really need to use specific component's name as a prefix, for example: ' user/userAPI', is that essential? could we use ' user/API'?

**Comment by i0natan** [comment]
It's a matter of style and there's probably no clear cut here but I personally suggest using the fully contextual object name, userService, because it's sometimes accessible not via file system. For example, when navigating through the code and arriving some code, the class name "API" won't tell you much and switching to file system view is not always convenient. The same can be said about generating memory dump or code coverage reports - all you have is the class/object name, not its parent folder name.

Makes sense?

**Comment by i0natan** [comment]
like here:
https://github.com/i0natan/nodebestpractices/blob/master/sections/projectstructre/breakintcomponents.md

**Comment by huquduy** [comment]
Yeah, you are right, i got some problems with my ideal
